---
# The name given to the PostgreSQL service (lowercase alphanumeric only).
db:
    # The type of your service (postgresql), which uses the format
    # 'type:version'. Be sure to consult the PostgreSQL documentation
    # (https://docs.platform.sh/configuration/services/postgresql.html#supported-versions)
    # when choosing a version. If you specify a version number which is not
    # available, the CLI will return an error.
    type: postgresql:12
    # The disk attribute is the size of the persistent disk (in MB) allocated to
    # the service.
    disk: 2048

# The name given to the Persistent Redis service (lowercase alphanumeric only).
redis:
    # The type of your service (redis-persistent), which uses the format
    # 'type:version'. Be sure to consult the Persistent Redis documentation
    # (https://docs.platform.sh/configuration/services/redis.html#supported-versions)
    # when choosing a version. If you specify a version number which is not
    # available, the CLI will return an error.
    type: redis-persistent:5.0
    # The disk attribute is the size of the persistent disk (in MB) allocated to
    # the service.
    disk: 256
